### ISSUE TITLE
ci.frostcast.net is offline

### ISSUE THREAD

**Issue by FourDown** [BanManagement/BanManager#160] opened 2015-02-19 16:56 UTC
http://ci.frostcast.net/job/BanManager/
http://ci.frostcast.net

Both give me a 503.

**Comment by confuser** [comment] 2015-02-19 16:58
Looks like the VPS that hosts it was booted.

It should be back up now.

**Comment by frdmn** [comment] 2016-02-29 11:35
James, I think the VPS has some little hiccups again. At least CloudFlare is using it's AlwaysOnline to render a cached version: 

![bildschirmfoto 2016-02-29 um 12 35 21](https://cloud.githubusercontent.com/assets/944459/13393315/eb859c32-dee0-11e5-978d-bbb27aeedf8b.png)

**Comment by confuser** [comment] 2016-02-29 11:38
Yes, duplicate of #533 I need to spin up a new machine as all of Frostcast's have been terminated with its shutdown. Didn't have time this weekend unfortunately.

**Closed** 2016-02-29 11:48 UTC
