### ISSUE TITLE
Slow startup.

### ISSUE THREAD

**Issue by bingoberra** [BanManagement/BanManager#507] opened 2016-01-24 18:15 UTC
This is not an issue with the database connection.
The plugin is REALLY slow on startup.

15.01 22:46:55 [Server] INFO Loaded 0 ip range bans into memory
15.01 22:46:55 [Server] INFO Loaded 86 ip bans into memory
15.01 22:46:38 [Server] INFO Loaded 6 mutes into memory
15.01 22:46:36 [Server] INFO Loaded 392 bans into memory
15.01 22:44:26 [Server] INFO Enabling BanManager v5.6.0

**READ THIS PART PLEASE:**
This was not an issue on earlier version. It takes about 2 1/2 minutes for it to load up! Which is a really long time for any plugin.

I'm using Spigot 1.8.7 & BanManager v5.6.0.

**Comment by confuser** [comment] 2016-01-24 19:31
Don't open duplicate issues, it's very annoying. Duplicate of #504

**Closed by confuser** 2016-01-24 19:31 UTC
