### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MrRedstone9000** [BanManagement/BanManager#736] opened 2017-06-10 10:42 UTC
When I type any of the punish commands, it just returns it back with the help text. No overriding plugins. Version 1.12 (Spigot)
`[12:38:07] [Server thread/INFO]: [BanManager] Enabling BanManager v5.14.0
[12:38:07] [Server thread/WARN]: 56 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - bm-local - Started.

[12:38:11] [Server thread/INFO]: [BanManager] Loaded 22 bans into memory
[12:38:13] [Server thread/INFO]: [BanManager] Loaded 2 mutes into memory
[12:38:13] [Server thread/ERROR]: Error occurred while enabling BanManager v5.14.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at me.confuser.banmanager.internal.guava.cache.LocalCache.<clinit>(LocalCache.java:77) ~[?:?]
	at me.confuser.banmanager.internal.guava.cache.LocalCache$LocalManualCache.<init>(LocalCache.java:4702) ~[?:?]
	at me.confuser.banmanager.internal.guava.cache.CacheBuilder.build(CacheBuilder.java:811) ~[?:?]
	at me.confuser.banmanager.storage.PlayerWarnStorage.<init>(PlayerWarnStorage.java:34) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:343) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:135) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

**Comment by McSwede** [comment] 2017-06-10 18:56
Can confirm plugin is not working on 1.12

**Comment by confuser** [comment] 2017-06-10 18:59
Try a dev build https://ci.frostcast.net/job/BanManager/

**Comment by McSwede** [comment] 2017-06-10 19:20
Thanks for quick response! Dev version works flawlessly

**Comment by confuser** [comment] 2017-06-14 10:20
I'll leave this open until a new release is done, in case anyone else has this issue.

**Comment by manuelgu** [comment] 2017-06-15 19:41
Using the latest dev build to fix the described issue gives me lots of `MySQLIntegrityConstraintViolationException: Column 'player_id' cannot be null`

**Comment by confuser** [comment] 2017-06-16 08:54
@manuelgu Can you provide the full stack trace?

**Comment by manuelgu** [comment] 2017-06-17 11:39
@confuser 
```
[11:39:12 WARN]: java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanRecord@31ecbe33: INSERT INTO `bm_player_ban_records` (`player_id` ,`reason` ,`expired` ,`actor_id` ,`pastActor_id` ,`pastCreated` ,`created` ,`createdReason` ) VALUES (?,?,?,?,?,?,?,?)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
[11:39:12 WARN]:        at me.confuser.banmanager.storage.PlayerBanRecordStorage.addRecord(PlayerBanRecordStorage.java:40)
[11:39:12 WARN]:        at me.confuser.banmanager.runnables.ExpiresSync.run(ExpiresSync.java:39)
[11:39:12 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.java:27)
[11:39:12 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[11:39:12 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:39:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:39:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:39:12 WARN]:        at java.lang.Thread.run(Thread.java:745)
[11:39:12 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'player_id' cannot be null
[11:39:12 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:39:12 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:39:12 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:39:12 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[11:39:12 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[11:39:12 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[11:39:12 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
[11:39:12 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[11:39:12 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[11:39:12 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[11:39:12 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[11:39:12 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
[11:39:12 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[11:39:12 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[11:39:12 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[11:39:12 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[11:39:12 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
[11:39:12 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[11:39:12 WARN]:        ... 10 more

```

**Comment by confuser** [comment] 2017-06-17 17:08
Looks like you've got a bad player ban record in your database, either without a player id, or the player is missing in the players table

**Comment by manuelgu** [comment] 2017-06-17 17:11
```
[11:44:01 WARN]: [BanManager] Missing player for ban 1, ignored
[11:44:01 WARN]: [BanManager] Missing player for ban 2, ignored
[11:44:01 WARN]: [BanManager] Missing player for ban 3, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 4, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 5, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 6, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 7, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 8, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 9, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 10, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 11, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 12, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 13, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 14, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 15, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 16, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 17, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 18, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 19, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 20, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 21, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 22, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 23, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 24, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 25, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 26, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 27, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 28, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 29, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 30, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 31, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 32, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 33, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 34, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 35, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 36, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 37, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 38, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 39, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 40, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 41, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 42, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 43, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 44, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 45, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 46, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 47, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 49, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 50, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 51, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 53, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 54, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 55, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 56, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 57, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 58, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 59, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 60, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 61, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 62, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 63, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 64, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 65, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 66, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 67, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 68, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 69, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 70, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 71, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 72, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 73, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 74, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 75, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 76, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 77, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 78, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 79, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 80, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 81, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 82, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 83, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 84, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 85, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 86, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 87, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 88, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 89, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 90, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 91, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 92, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 93, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 94, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 95, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 96, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 97, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 98, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 99, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 101, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 104, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 106, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 109, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 117, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 127, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 168, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 179, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 180, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 181, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 185, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 189, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 191, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 193, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 202, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 203, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 204, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 205, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 206, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 207, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 208, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 214, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 218, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 222, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 224, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 227, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 231, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 237, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 238, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 239, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 243, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 245, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 246, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 247, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 248, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 249, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 250, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 253, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 254, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 255, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 258, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 259, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 260, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 261, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 262, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 266, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 268, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 269, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 273, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 274, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 277, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 285, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 286, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 288, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 298, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 299, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 300, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 309, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 311, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 312, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 314, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 318, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 319, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 320, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 321, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 337, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 346, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 347, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 348, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 354, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 355, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 356, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 358, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 359, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 367, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 382, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 383, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 384, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 385, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 386, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 387, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 388, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 389, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 390, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 391, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 393, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 394, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 396, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 397, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 398, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 399, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 402, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 403, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 415, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 424, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 428, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 430, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 431, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 432, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 433, ignored
[11:44:02 WARN]: [BanManager] Missing player for ban 434, ignored
[11:44:02 INFO]: [BanManager] Loaded 0 bans into memory
[11:44:02 INFO]: [BanManager] Loaded 0 mutes into memory

```

I believe so. Happened after upgrading to latest BanManager version - worked fine before.

**Comment by confuser** [comment] 2017-06-17 17:39
@manuelgu Have you touched your players table at all? There's nothing in the latest version that would cause the players table to be cleared.

**Comment by manuelgu** [comment] 2017-06-17 22:03
@confuser Nope, I haven't.The `bm_player_ban_records` table does have entries too for (all) the bans.

**Comment by MrRedstone9000** [comment] 2017-06-18 04:19
This can be marked solved if required, solution from @confuser: Try a dev build https://ci.frostcast.net/job/BanManager/

**Comment by manuelgu** [comment] 2017-06-18 15:22
@confuser 

There are no entries with no player_id
```
mysql> select * from bm_player_bans where player_id is null;
Empty set (0.00 sec)

mysql> select * from bm_player_ban_records where player_id is null;
Empty set (0.00 sec)

```

36 permanent bans, that seems about right
```
mysql> select count(*) from bm_player_ban_records join bm_player_bans on (bm_player_ban_records.player_id = bm_player_bans.player_id);
+----------+
| count(*) |
+----------+
|       36 |
+----------+
1 row in set (0.00 sec)
```

**Comment by confuser** [comment] 2017-06-18 15:24
@manuelgu The issue is player_id references back to the players table. It's complaining that it can't find them, e.g. it's performing a select/join on the players table using player_id.

**Comment by manuelgu** [comment] 2017-06-18 15:25
@confuser What do you think how that happened? Any way to fix it? The data appears to be there.

**Comment by confuser** [comment] 2017-06-18 15:28
@manuelgu Data appears to be where? Yes, it's in the bans table, but it **requires** the player data in the players table to retrieve their name etc. Something/someone removed them from your players table. There's nothing in the plugin I can think of that would cause that.

**Comment by manuelgu** [comment] 2017-06-18 15:31
@confuser I'm the only one with db access and haven't ever touched it.

The player data in the players table (bm_players (?)) appears to be there.
```
mysql> select count(*) from bm_players;
+----------+
| count(*) |
+----------+
|     9272 |
+----------+
1 row in set (0.00 sec)
```
I know that the player_id is the primary key and referenced as a foreign key in the other tables.

**Comment by manuelgu** [comment] 2017-07-27 15:27
Any update on this? @confuser

**Comment by confuser** [comment] 2017-07-27 15:46
Afraid not as it seems to be a data issue on the surface. Can you run the following query to see if it returns any results?

```
SELECT *, HEX('player_id') FROM `bm_player_bans` b LEFT JOIN `bm_players` p ON b.player_id = p.id WHERE p.id IS NULL
```

**Comment by manuelgu** [comment] 2017-07-27 17:46
@confuser It returns 198 rows successfully.

**Comment by confuser** [comment] 2017-07-29 08:01
It should be returning 0. It means you're missing players in your players table. I'm working on a utility command that should help resolve it.

**Comment by confuser** [comment] 2017-07-29 12:59
@manuelgu https://ci.frostcast.net/job/BanManager/15/ and run /bmutils missingplayers, check the logs, and restart the server.

**Comment by manuelgu** [comment] 2017-07-29 14:35
@confuser Says to have found 811 missing players - console get's spammed with https://hastebin.com/okuxexepec.md (see how the UUIDs are unlikely to be from players, their first and second part matches)

**Comment by manuelgu** [comment] 2017-07-29 14:36
Also, it has resolved 0 players.

**Comment by confuser** [comment] 2017-07-29 14:36
Your data is really messed up. Are you running in offline mode?

**Comment by manuelgu** [comment] 2017-07-29 15:02
No, online mode. Always have been

**Comment by confuser** [comment] 2017-07-29 17:00
Well based on that error, you seem to have punishments that are associated to offline players, which are also missing from your players table.

**Comment by manuelgu** [comment] 2017-07-29 18:23
@confuser I'm running in online mode definitely, but behind [https://github.com/LilyPad/GoLilyPad](LilyPad). There are no known issues about a broken uuid forwarding feature.

Would it help if you had a look at the database set yourself?

**Comment by rautamiekka** [comment] 2017-07-29 20:00
^ FYI: the link to LilyPad is broken, it points to a non-existing place under this very project, not LilyPad.

**Comment by MrRedstone9000** [comment] 2017-07-30 01:56
Side note: the problem is fixed, had to use beta

**Comment by confuser** [comment] 2017-08-06 10:21
@manuelgu Probably, but no promises, your data sounds like it's corrupted. I'm going to close this as the original problem this issue was opened for is resolved.

**Closed by confuser** 2017-08-06 10:21 UTC
Labels: question

**Comment by manuelgu** [comment] 2017-08-06 12:43
@confuser want me to mail you a zip of a mysqldump?
