### ISSUE TITLE
Weird startup issue after updating to latest

### ISSUE THREAD

**Issue by tyler2k15** [BanManagement/BanManager#447] opened 2015-11-07 14:25 UTC
[09:16:17] [Server thread/INFO] [me.confuser.banmanager.BanManager/]: [BanManager] Enabling BanManager v5.7.1
[09:16:17] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling BanManager v5.7.1 (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.configs.HooksConfig.<init>(HooksConfig.java:38) ~[?:?]
	at me.confuser.banmanager.configs.DefaultConfig.afterLoad(DefaultConfig.java:87) ~[?:?]
	at me.confuser.banmanager.bukkitutil.configs.Config.load(Config.java:98) ~[?:?]
	at me.confuser.banmanager.BanManager.setupConfigs(BanManager.java:322) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:100) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.133]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.133]

**Comment by tyler2k15** [comment] 2015-11-07 15:19
I have increased my max connections to 500, but I am getting errors from servers saying there are too many connections. before updating our servers to the latest we had no issues. Now it is using all connections and i cannot even connect to it via local host ssh without max connections error

**Comment by EvilOlaf** [comment] 2015-11-07 17:10
MySQL and SSH are complete different daemons. Must be something else.

**Comment by tyler2k15** [comment] 2015-11-08 07:27
I am aware the MySQL and SSH are different daemons. IF you aren't aware, however, you can use SSH to login to the MySQL server using command 'mysql -u [user] -p'

**Comment by tyler2k15** [comment] 2015-11-08 07:28
After reverting back to version 5.3.0 which is what we were running prior, connections are now ~100-150 versus where the updated version it was maxing out connections even with increasing max connections to 3000

**Comment by EvilOlaf** [comment] 2015-11-08 08:16
Okey then that was just a misapprehension.

**Comment by confuser** [comment] 2015-11-08 10:45
The first issue would only occur if `hooks` was removed from your config.

As for the max connections, the plugin shouldn't be opening more than defined as the max in the config.

Is 5.3 the earliest version you found that didn't have this problem?

**Comment by tyler2k15** [comment] 2015-11-10 11:45
I have not tested any versions between 5.3 and 5.7.1.

I can try to do that during non-peak times and see if I can come up with something and let you know.

**Comment by confuser** [comment] 2015-11-10 11:46
@tyler2k15 if you can narrow down the version, I can then narrow down what changes were made between that version and v5.7 to find the cause, and hopefully offer a fix/solution.

**Comment by confuser** [comment] 2015-11-10 11:54
@tyler2k15 I've reverted a change that was made as part of a possible fix for a different issue. This may be causing this problem.

http://ci.frostcast.net/ Build 208+

**Comment by tyler2k15** [comment] 2015-11-10 12:21
To figure out which version is causing the issue I have downloaded version 1.6, 1.6.1, and 1.7.0 to test on a low-populated server.

'Output of SHOW PROCESSLIST;' on 1.6.0 121 rows in set (0.00 sec)
'Output of SHOW PROCESSLIST;' on 1.6.1 121 rows in set (0.00 sec)
'Output of SHOW PROCESSLIST;' on 1.7.0

**Comment by tyler2k15** [comment] 2015-11-10 12:40
@confuser Since my tests seemed to do no good running them on a server with low traffic, I'll test the build 208 on the entire network and inform you of the results

**Comment by tyler2k15** [comment] 2015-11-10 12:55
After putting all servers to build 208 it seemed fine at first
Then the connections start increasing..

Went from 118 to 300 a few minutes later, Now to 376. Everytime I run the show process list in MySQL it shows higher number

**Comment by confuser** [comment] 2015-11-10 12:56
What is your max connections set to in `config.yml` and how many servers are you running?

**Comment by tyler2k15** [comment] 2015-11-10 12:57
Each server is creating unlimited number of connections:
http://prntscr.com/915nvt
Max connections: 10


12 servers

**Comment by tyler2k15** [comment] 2015-11-10 13:13
I found an interesting thing..

Our Modsauce 2 server timed everyone out while the SQL connections were up to 1000. I manually restarted it due to this, and now after if went down to 90 connections and now that server is up and running again it is slowly going back up. 

Max connections of this server, and all servers, is set to 10 in all three locations.

Config: https://gist.github.com/tyler2k15/3ed1fb9f33c825c15695

**Comment by confuser** [comment] 2015-11-10 13:26
Which database is having the connection problems, local or external? I notice from the config, you're using both.

**Comment by tyler2k15** [comment] 2015-11-10 13:26
it is the ban manager_Modsauce config for the Modsauce server only that seems to open endless connections

**Comment by confuser** [comment] 2015-11-10 13:29
I'm afraid I'm not familiar with `Modsauce 2`. Is it a modded server, running under something like Cauldron?

To confirm, the other servers are running craftbukkit/spigot on v5.7 and do not have a connection problem, only the Modsauce server?

**Comment by tyler2k15** [comment] 2015-11-10 13:38
All servers are modded, running cauldron. The only  server not running modded is the hub. All servers are connected to the "Network" database. Umm, All but two servers are on the same box.

Mod sauce 2 is on it's own box but all servers connect to the main box's MySQL Database for Banamanager.

**Comment by tyler2k15** [comment] 2015-11-10 13:39
http://bans.tronopolis.one

**Comment by confuser** [comment] 2015-11-10 14:20
Well now that the cause has been narrowed down somewhat, are there any MySQL based plugins you are running on Modsauce but not the other servers? Anything that interacts with BM, either via the API, or reads banmanager data from the database itself?

**Comment by tyler2k15** [comment] 2015-11-10 21:43
The only thing would be prism but that's on all servers.

**Comment by confuser** [comment] 2015-11-11 09:59
How strange. Are they all running the same build of cauldron? How are you updating BanManager, a full restart or reloading via a plugin manager?

**Comment by tyler2k15** [comment] 2015-11-12 19:51
They are not all running the same exact version. But there is at least one server running the same as Modsauce without the issue :/

**Comment by tyler2k15** [comment] 2015-11-12 19:51
Reloading by restarting server

**Comment by tyler2k15** [comment] 2015-11-12 19:53
Cauldron versions below:

'1492.149 - Agrarian Skies 2'
'1492.150 - Modsauce2, CrundeeCraft'
'1448.133 - Hubris, RR3: Project Flux, Direwolf and Infinity'

**Comment by tyler2k15** [comment] 2015-11-16 06:04
Found anything out as to why it would be isolated to this server?

**Comment by confuser** [comment] 2015-11-16 10:21
I haven't yet, no. I can't seem to see anything that would cause this issue to occur.

Are you running the same Java version on all servers? Is there anything config/system wise that is perhaps different?

**Comment by tyler2k15** [comment] 2015-11-16 17:54
The server running Modsauce is located in france, meanwhile the other 2 physical servers are located in a datacenter in Canada.

Java version is 1.8.0_66-b17 on all 3 physical servers. I really can't think what is different that would cause such a database issue.

Running same version of SQL (MariaDB) - 10.0.22-MariaDB-0+deb8u1 - (Debian)

All Running Debian 8.2

Kernel Version: Linux 3.14.32-xxxx-grs-ipv6-64 on x86_64 (Same on all)

All Available package updates installed

**Comment by Iceee** [comment] 2015-11-25 16:29
I'm seeing BanManager not obey the max connections setting.  One of my servers has 79 banmanager connections opened.

**Comment by Iceee** [comment] 2015-11-25 19:27
Update:

It looks like it created all of those connections when our host rebooted a router, causing it to lose connection to the DB.  Multiple servers spawned up to 300 connections, ultimately hitting the DB max-connections limit.  Is there a potential issue with it not closing attempted connections?

**Comment by confuser** [comment] 2015-11-26 09:50
Perhaps. The connection handling is however lower level handled by a 3rd party library, ORMLite. Unfortunately the developer isn't overly active. This isn't the only problem I've encountered with it thus far.

**Comment by Iceee** [comment] 2015-11-27 05:38
Try the following:
1) Break the connection between BanManager and the DB during runtime
2) Join a lot / force connections
3) Check the number of connections

**Comment by confuser** [comment] 2015-11-27 10:38
Thanks @Iceee I'll try to reproduce it this weekend.

**Comment by Spirit55555** [comment] 2015-12-07 18:50
I have the same problem with too many connections. The problem appeared out of nowhere. Running latest BM and Spigot versions.

http://ci.frostcast.net seems to be down or under maintenance, so I am not able to download the newest build.

**Comment by confuser** [comment] 2015-12-11 10:48
@Iceee I couldn't reproduce this locally I'm afraid. Started a server, stopped the MySQL service spam ran /bminfo around 30 - 40 times within quick succession, started MySQL. Number of connections was only ever 10, the maximum set in the default config.

**Comment by Iceee** [comment] 2015-12-11 15:31
What about attempting to join very quickly?

**Comment by confuser** [comment] 2015-12-12 11:51
That was a little more difficult to simulate locally, as the connections were waiting for time outs, it slowed down the rate I could join with a single client.

**Comment by confuser** [comment] 2015-12-19 12:37
Perhaps the fastest solution to this is to pull in a library specifically built to handle connection pooling, rather than use ORMLite's inbuilt pool.

**Comment by confuser** [comment] 2015-12-19 13:54
Build 21+ running BoneCP, a different connection pool

http://ci.frostcast.net/job/BanManager/

Feedback appreciated

**Comment by Posse1** [comment] 2015-12-19 15:55
I have installed it on my server. monitoring now for max connections issue.

**Comment by Posse1** [comment] 2015-12-19 16:50
So far seems good. It sometimes takes a few hours to start spamming connections. I will report back later today.

**Comment by vemacs** [comment] 2015-12-19 17:10
HikariCP seems to be more popular among the hipster database development crowd. Not particularly difficult to migrate to that from BoneCP.

**Comment by confuser** [comment] 2015-12-19 18:56
Wasn't aware of that, thanks @vemacs, switched.

**Comment by Posse1** [comment] 2015-12-20 03:07
So far its been working well. Trying build #26 now with hikaricp

**Comment by confuser** [comment] 2015-12-20 10:37
Thanks for the feedback @Posse1 :+1:

**Comment by confuser** [comment] 2015-12-21 16:44
@Posse1 any further issues?

**Comment by Posse1** [comment] 2015-12-21 16:53
No further issues, everything is running perfectly fine with hikaricp

**Comment by confuser** [comment] 2015-12-21 16:55
Awesome, I'll release v5.8.0 officially shortly. Thanks to everyone helping with testing.

**Closed by confuser** 2015-12-21 16:55 UTC
Labels: bug
