### ISSUE TITLE
BanManager v5.4.1 generated an exception while executing task 15

### ISSUE THREAD

**Issue by CurePindal** [BanManagement/BanManager#283] opened 2015-05-24 14:55 UTC
Unfortunatly I have no clue why this happed after the server startup. Nor if its serious or not. Didnt see this with v5.4.1.
Anybody who can give me a hint whats wrong here?
Thanks!

[16:24:25] [main/INFO]: Forge Mod Loader version 7.10.88.1307 for Minecraft 1.7.10 loading
[16:24:25] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_45, running on Linux:amd64:3.13.0-53-generic, installed at /opt/jre1.8.0_45
(Its a newer Cauldron-server).

[16:26:34] [Craft Scheduler Thread - 1/WARN]: Exception in thread "Craft Scheduler Thread - 1" 
[16:26:34] [Craft Scheduler Thread - 1/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.4.1 generated an exception while executing task 15
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.PlayerBanData
	at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
	at me.confuser.banmanager.runnables.BanSync.newBans(BanSync.java:52)
	at me.confuser.banmanager.runnables.BanSync.run(BanSync.java:31)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
	at com.mysql.jdbc.ResultSetImpl.first(ResultSetImpl.java:1164)
	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.first(JdbcDatabaseResults.java:58)
	at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:79)
	at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
	... 7 more

**Comment by confuser** [comment] 2015-05-24 16:49
Duplicate of #276

**Closed by confuser** 2015-05-24 16:49 UTC
Labels: duplicate
