### ISSUE TITLE
Bungeecord unable to retreive uuid of player

### ISSUE THREAD

**Issue by z1haze** [BanManagement/BanManager#272] opened 2015-05-15 21:09 UTC
This is on a bungee server network. The servers are in offline mode and in bungeecord mode. It seems it is unable tocontact mojang for the uuid, and I get the response unable to find <player>, are you sure they exist?" I found a recent ticket and updated to the latest version you have linked to your jenkins but it didnt fix.

15.05 17:07:25 [Server] WARN ... 9 more
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
15.05 17:07:25 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
15.05 17:07:25 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
15.05 17:07:25 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
15.05 17:07:25 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
15.05 17:07:25 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15.05 17:07:25 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\xA9\x16\xAB\xBD\xA7\xADO\xA7\xA4\x97O\xA6\xA4\xA5\x9A\x81' for key 'PRIMARY'
15.05 17:07:25 [Server] WARN at java.lang.Thread.run(Thread.java:745)
15.05 17:07:25 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
15.05 17:07:25 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
15.05 17:07:25 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
15.05 17:07:25 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.commands.BanCommand$1.run(BanCommand.java:102)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.storage.PlayerStorage.retrieve(PlayerStorage.java:195)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
15.05 17:07:25 [Server] WARN at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
15.05 17:07:25 [Server] WARN java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerData@3829ada2: INSERT INTO `bm_players` (`id` ,`name` ,`ip` ,`lastSeen` ) VALUES (?,?,?,?)

**Comment by confuser** [comment] 2015-05-15 21:19
Are you running bungge cord in offline mode too, or online mode? You are using the v5.5.0-SNAPSHOT?

**Comment by z1haze** [comment] 2015-05-15 21:20
Bungeecord is in online mode and ip forward is true. My server just can't get to Mojang to retrieve uuid

**Comment by roastnewt** [comment] 2015-05-15 21:25
Does your spigot.yml have bungeecord: true?

**Comment by z1haze** [comment] 2015-05-15 21:28
yes, on all 3 servers

---- On Fri, 15 May 2015 17:25:18 -0400 Clayton &lt;notifications@github.com&gt; wrote ---- 

Does your spigot.yml have bungeecord: true?

**Comment by voigtman** [comment] 2015-05-16 18:38
Do you have ip_forward set to true in your bungee config? 
http://www.spigotmc.org/wiki/bungeecord-ip-forwarding/

**Comment by confuser** [comment] 2015-05-18 10:29
Duplicate of #271

**Closed by confuser** 2015-05-18 10:29 UTC
Labels: duplicate
