### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by CloudeLecaw** [BanManagement/BanManager#331] opened 2015-07-23 06:28 UTC
i dont knwo why this happens, but sometime the console give me this text:
00:30:35] [Craft Scheduler Thread - 36/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.6.0 generated an exception while executing task 24
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.setRowPositionValidity(ResultSetImpl.java:852)
        at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7183)
        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.next(JdbcDatabaseResults.java:64)
        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.first(JdbcDatabaseResults.java:56)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:79)
        at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
        at me.confuser.banmanager.runnables.BanSync.newBans(BanSync.java:48)
        at me.confuser.banmanager.runnables.BanSync.run(BanSync.java:32)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by confuser** [comment] 2015-07-23 09:59
Duplicate of #321

**Closed by confuser** 2015-07-23 09:59 UTC
