### ISSUE TITLE
Config setting createNoteReasons broken

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#609] opened 2016-05-17 17:54 UTC
`createNoteReasons` is set to `false` but creates notes anyways.

BM 5.9.0

**Comment by confuser** [comment] 2016-05-18 09:19
Duplicate of #570 

This is already fixed in a developer build.

**Closed by confuser** 2016-05-18 09:19 UTC
Labels: invalid

**Comment by EvilOlaf** [comment] 2016-05-18 15:23
Woops, my bad.
