### ISSUE TITLE
If i try to ban someone

### ISSUE THREAD

**Issue by RedOreGaming** [BanManagement/BanManager#345] opened 2015-08-01 21:46 UTC
I tried to ban someone an this error shows up in the Console:
And this Ingame: Kilian_1234 bot fround, are you sure they exist? (and yes he exists!)
http://prntscr.com/7zqse7

**Comment by confuser** [comment] 2015-08-02 10:36
Duplicate of #334

**Closed by confuser** 2015-08-02 10:36 UTC
