### ISSUE TITLE
Excessive connection spam

### ISSUE THREAD

**Issue by vemacs** [BanManagement/BanManager#473] opened 2015-12-16 01:38 UTC
![](https://i.imgur.com/lui8b8v.png)

I tried lowering max-connections to no avail. BanManager is saturating the database server with connections (which are eventually pruned, but it's still annoying) during startup. I have not had this issue with any other plugin that uses a connection pool of some form.

**Comment by confuser** [comment] 2015-12-19 09:26
Duplicate of #447

**Closed by confuser** 2015-12-19 09:26 UTC
