### ISSUE TITLE
Commands Overwritten

### ISSUE THREAD

**Issue by Araton10** [BanManagement/BanManager#619] opened 2016-06-06 15:12 UTC
Hi man,
I Use ReporterGUI for manage the report with an Web-Interface, Ban Manager Overwritten the command /report and blocks the /report command of ReporterGUI.

Can you have a solution for this problem?

**Comment by confuser** [comment] 2016-06-06 15:15
Duplicate of #486

**Closed by confuser** 2016-06-06 15:15 UTC
Labels: question
