### ISSUE TITLE
Errors from banmanager

### ISSUE THREAD

**Issue by Posse1** [BanManagement/BanManager#449] opened 2015-11-09 03:18 UTC
Hi, i am using v5.7.1 with spigot 1.8.8 and getting the following error can I find out whats causing it?

[22:09:42 WARN]: java.lang.IllegalStateException: Errors getting more results of
 class me.confuser.banmanager.data.IpBanData
[22:09:42 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIt
erator.hasNext(SelectIterator.java:103)
[22:09:42 WARN]:        at me.confuser.banmanager.runnables.IpSync.newBans(IpSyn
c.java:32)
[22:09:42 WARN]:        at me.confuser.banmanager.runnables.IpSync.run(IpSync.ja
va:22)
[22:09:42 WARN]:        at me.confuser.banmanager.runnables.Runner.run(Runner.ja
va:28)
[22:09:42 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.ru
n(CraftTask.java:71)
[22:09:42 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTa
sk.run(CraftAsyncTask.java:53)
[22:09:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[22:09:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[22:09:42 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:09:42 WARN]: Caused by: java.sql.SQLException: Operation not allowed after R
esultSet closed
[22:09:42 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1073)
[22:09:42 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:987)
[22:09:42 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:982)
[22:09:42 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:927)
[22:09:42 WARN]:        at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImp
l.java:794)
[22:09:42 WARN]:        at com.mysql.jdbc.ResultSetImpl.first(ResultSetImpl.java
:1164)
[22:09:42 WARN]:        at me.confuser.banmanager.internal.ormlite.jdbc.JdbcData
baseResults.first(JdbcDatabaseResults.java:58)
[22:09:42 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIt
erator.hasNextThrow(SelectIterator.java:79)
[22:09:42 WARN]:        at me.confuser.banmanager.internal.ormlite.stmt.SelectIt
erator.hasNext(SelectIterator.java:98)
[22:09:42 WARN]:        ... 8 more

**Comment by EvilOlaf** [comment] 2015-11-09 06:39
Weird, this should have been fixed afair?

https://github.com/BanManagement/BanManager/issues/321

**Comment by confuser** [comment] 2015-11-09 11:40
Duplicate of #446

**Closed by confuser** 2015-11-09 11:40 UTC
