### ISSUE TITLE
Problem with Format "year"

### ISSUE THREAD

**Issue by Nico180902** [BanManagement/BanManager#497] opened 2016-01-09 09:46 UTC
Hi confuserr,

I have got a question about your plugin BanManager. (This question ist not in the FAQ):

Your plugin works perfect and I have no great Problems with it, but if i type /tempban {Player} 1y Trololol -> Then in the Chat it will be 366 days and not 1 year. For example if I type /tempban {Player} 10y Then he will be banned for 3566 days or something, but I want that it's in the Chat shown as "Nico180902 banned {Player} for 10 years" and not "Nico180902 banned {Player} for 3656 days" or something

Some Screenshots: http://prntscr.com/9nvgwc http://prntscr.com/9nvhd6

Sorry for bad English, I'm german. If you dont understand the question, then I will tranlate it

**Comment by confuser** [comment] 2016-01-09 09:53
Duplicate of #452

**Comment by Nico180902** [comment] 2016-01-09 09:57
It's not a Duplicate

**Comment by confuser** [comment] 2016-01-09 10:01
Yes, it is. The cause of the bug you've reported is detailed in #452

**Comment by EvilOlaf** [comment] 2016-01-09 10:03
I am not sure if this is really related to https://github.com/BanManagement/BanManager/issues/452 . Maybe partially.
If this is really the summary of the async worker delay, why are the 23 hours and 59 minutes missing to round the year up?

**Comment by confuser** [comment] 2016-01-09 10:04
I'm not sure why you would want to temporary ban someone for such a length of time rather than just permanently ban them, but I'll take a look

**Comment by EvilOlaf** [comment] 2016-01-09 10:05
I wanted to write something similar in first place xD

**Comment by Nico180902** [comment] 2016-01-09 10:25
Yes. for us in Austria its silly if we ban a player permanent. He should be banned for 1 year and then he should come again and so he can play on the server and lern about his fairlure. because in 1 year many things can the changed. 

This is important too:
No format over day works, not week, not month. So if i type "ban player 1mon" in the chat its 30 days. I think the fault is the update v5.0.

**Comment by Nico180902** [comment] 2016-01-09 10:46
And have you got the reason?

**Closed** 2016-01-30 16:30 UTC
Labels: bug

**Comment by Nico180902** [comment] 2016-01-30 16:47
No Update? What should I do now?
On my Server nothing changed

**Comment by EvilOlaf** [comment] 2016-01-30 16:54
How should it?

You either can download the source now and compile the plugin by yourself or look for a Jenkins CI that has dev builds from BanManager or wait till a new version will be officially released on dev.bukkit.org

**Comment by Nico180902** [comment] 2016-01-30 16:57
When is the new Version going to release?

**Comment by EvilOlaf** [comment] 2016-01-30 17:01
This might be answered by @confuser :)

**Comment by Nico180902** [comment] 2016-01-30 17:04
Yes i'm waiting...

**Comment by confuser** [comment] 2016-01-30 17:06
If you can't wait:

http://ci.frostcast.net/job/BanManager/

**Comment by Nico180902** [comment] 2016-01-30 17:23
But @confuser I have one silly question:
Is it possible to tempban for 100 years? (/tempban {Player} 100y :)

**Comment by Nico180902** [comment] 2016-01-30 17:26
So can you add the Feature in a Future Version?

**Comment by confuser** [comment] 2016-01-30 17:28
No it's not possible, there's a maximum limit of 20 years. Just permanently ban them instead. I don't understand why you'd want to ban someone for 100 years, they'd probably be dead by the time it expired, and your server probably wouldn't exist then anyway.

**Comment by Nico180902** [comment] 2016-01-30 17:29
Yes, I want it to make a fun Gadget for the Server.. A Server had this Feature too, for me it was awesome :D
