### ISSUE TITLE
Error in my Console:

### ISSUE THREAD

**Issue by RedOreGaming** [BanManagement/BanManager#393] opened 2015-09-12 11:17 UTC
Hey,
I think i Found a Issue:
Here is my Console:
http://hastebin.com/riyajugexe.avrasm

**Comment by EvilOlaf** [comment] 2015-09-12 11:22
Probably duplicate of https://github.com/BanManagement/BanManager/issues/321

**Comment by confuser** [comment] 2015-09-12 16:53
Duplicate of #321

**Closed by confuser** 2015-09-12 16:53 UTC
