### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Adnan1234** [BanManagement/BanManager#506] opened 2016-01-24 05:05 UTC
On startup I get this error.
http://paste.ubuntu.com/14627793/

**Comment by confuser** [comment] 2016-01-27 13:06
That doesn't appear to be on start up but rather when a player joins the server.

Does this happen all the time? It's most likely caused by MySQL forcefully closing the connection.

**Comment by confuser** [comment] 2016-02-07 10:15
Closed due to lack of reply

**Closed by confuser** 2016-02-07 10:15 UTC
