### ISSUE TITLE
OnEnable NullPointerException

### ISSUE THREAD

**Issue by Maescool** [BanManagement/BanManager#335] opened 2015-07-28 11:42 UTC
Suddenly have this error on my servers
```
[04:01:02] [Server thread/INFO]: [BanManager] Enabling BanManager v5.6.0
[04:01:02] [Server thread/ERROR]: Error occurred while enabling BanManager v5.6.0 (Is it up to date?)
java.lang.NullPointerException
        at me.confuser.banmanager.storage.PlayerBanStorage.<init>(PlayerBanStorage.java:49) ~[?:?]
        at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:405) ~[?:?]
        at me.confuser.banmanager.BanManager.onEnable(BanManager.java:125) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at com.ryanclancy000.plugman.utilities.Utilities.loadPlugin(Utilities.java:294) [PlugMan.jar:?]
        at com.ryanclancy000.plugman.utilities.Utilities.reloadCommand(Utilities.java:423) [PlugMan.jar:?]
        at com.ryanclancy000.plugman.PlugManCommands.onCommand(PlugManCommands.java:82) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```
Also had some dup id's but banmanager is acting up lately (guess acting up cause of mojang api issues)

**Comment by confuser** [comment] 2015-07-28 11:55
Duplicate of #330 

Contains potential solution.

Do you have any other systems editing your BM data, external to the plugin? Something is removing rows from your players table and not removing any associated data. BM does not delete any data within the players table.

**Closed by confuser** 2015-07-28 11:55 UTC
