### ISSUE TITLE
The function "report"

### ISSUE THREAD

**Issue by Arkazium** [BanManagement/BanManager#630] opened 2016-06-26 19:12 UTC
Hello, there is a function report in BanManager but I use an others plugin for that.
In the future, can you make an option to choose this function or not. That will be very useful for others !

Thanks & congratulations for your plugin !

**Comment by EvilOlaf** [comment] 2016-06-26 19:22
Check the other (closed) issue reports to fix this.

**Comment by confuser** [comment] 2016-06-27 13:32
Duplicate of #486

**Closed by confuser** 2016-06-27 13:32 UTC
