### ISSUE TITLE
Tab autocomplate problems on Thermos 1.7.10

### ISSUE THREAD

**Issue by vulunijo** [BanManagement/BanManager#590] opened 2016-04-17 16:59 UTC
I'm using thermos 1.7.10 and nickname tab-autocomplate not working for banmanager commands.
Nick tab-complate on other plugin commands work fine.
Banmanager last version.

**Comment by confuser** [comment] 2016-04-18 09:04
Can you please elaborate on the problem? Tab completion does work, however, if you've just installed the plugin, you won't have all players show up until they've joined the server at least once.

**Comment by vulunijo** [comment] 2016-04-18 11:31
You're talking about offline autocomplate?
I mean when a player is on a server, you can write a command and then part of the nickname, which should be complemented by pressing TAB. It does not work with the Banmanager commands.

**Comment by confuser** [comment] 2016-04-19 09:23
What other plugins do you have installed? I'm not able to reproduce this issue with 1.7.10. Are you using Spigot, or some other server implementation?

**Comment by vursanity** [comment] 2016-04-19 22:54
Yes i am using spigot

**Comment by EvilOlaf** [comment] 2016-04-20 07:06
I assume that @confuser tested this with Spigot 1.7.10 as well so it is probably not the server software but another plugin that interferes. So what other plugins do you use?

**Comment by vursanity** [comment] 2016-04-20 15:42
https://i.gyazo.com/6ef8ada2d00db6d0dc481bc93b43c59c.png
https://i.gyazo.com/e52a245bb39b5bce503376e6cc291f70.png

@confuser

**Comment by confuser** [comment] 2016-04-22 09:17
Can you provide the output of `/version` please

**Comment by vursanity** [comment] 2016-04-23 01:05
@confuser Here's the /version
https://i.gyazo.com/a6a3ad182c7384a9469e06a4ec737701.png

**Comment by vulunijo** [comment] 2016-04-23 19:36
@confuser  This server is running Thermos | https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.55 (MC: 1.7.10)

i have only essetnials worldedit and worldguard!
with older ban manager versions tabcomplate works fine!

**Comment by vulunijo** [comment] 2016-04-23 19:36
@confuser  This server is running Thermos | https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.55 (MC: 1.7.10)

i have only essetnials worldedit and worldguard!
with older ban manager versions tabcomplate works fine!

**Comment by confuser** [comment] 2016-04-25 10:15
@vursanity looks like you're running a custom version of Spigot? You too @vulunijo. I haven't worked with modded servers in a while (not since tekkit lite). I'll take a look at Thermos and see if I can find what's causing the incompatibility.

**Comment by acidbyt3** [comment] 2016-05-03 12:55
I've experienced this on spigot 1.9.2. I believe this may be due to another plugin that has /ban or /mute commands (these are the ones that act up for me)

The issue does not seem to happen if I do /bmban [tab] or /bmmute [tab] - it auto completes as any other BanManager command would, which leads me to believe it may be related to me having essentials which could be interfering with /ban and /mute auto-completes?

Other plugins I have installed that may possibly interfere with tab: ProtocolLib, EzProtector

**Comment by confuser** [comment] 2016-05-03 13:17
@acidbyt3 Are you using EssentialsX? I never had this problem with normal Essentials. Perhaps there's a change in the forked version that is causing this.

**Comment by acidbyt3** [comment] 2016-05-03 13:49
I'm using normal Essentials. I'm not even sure if this is what's causing the problem, was just a wild guess since its those two commands that are also used by Essentials. However, /kick is also used by Essentials and that one works fine (but the TAB completion isn't case-sensitive, unlike the other /bm- commands).

Speaking of case-sensitive TAB completion, is that just me? c[tab] auto-completes "cactus" but not "Carrot", for example.

**Comment by confuser** [comment] 2016-05-03 14:06
Offline name tab completion is case sensitive in BM, due to the sheer amount of players most servers have stored in their databases.

I'll try reproducing this again with spigot 1.9.2 with the plugins you've listed @acidbyt3

**Comment by acidbyt3** [comment] 2016-05-03 14:10
Didn't think of that (we're still a small server) but that makes perfect sense.

Thank you, let me know if there's any more info I can get you that could help diagnose this.

**Comment by confuser** [comment] 2016-05-21 14:22
I still can't reproduce this on Spigot 1.9.4, it behaves as expected with `offlineAutoComplete` enabled and disabled.

```
Plugins (6): PermissionsEx, PlugMan, Vault, BarAPI, BanManager, ReportsLogger
```

**Comment by fijodi** [comment] 2016-06-04 17:28
https://bukkit.org/threads/easy-no-api-setting-up-custom-tab-completion.299956/

**Comment by confuser** [comment] 2016-06-04 17:42
@fijodi what relevance does that have to do with this issue? I'm well aware of how to implement custom tabs and find that rather patronising. How else do you think this feature is working? This issue exists because there is something interfering with the vanilla API.

**Comment by acidbyt3** [comment] 2016-06-18 08:50
Sorry for the late reply. I'm currently on 1.10 with the latest BanManager version and it's still behaving the same way: /ban, /tempban and /mute don't tab-complete for me, from what I can tell every other command behaves as expected, even /tempmute. This remains true on all our 4 servers.

Something else I also noticed, somewhat related to this, when a new player joins the server, it won't tab-complete their name for any BM command, not even /bminfo. However, if we manually type the player's name, the command runs fine and it returns the player's info/punishes the player as expected.

No errors on the console.

**Comment by confuser** [comment] 2016-06-18 11:05
> Something else I also noticed, somewhat related to this, when a new player joins the server, it won't tab-complete their name for any BM command, not even /bminfo. However, if we manually type the player's name, the command runs fine and it returns the player's info/punishes the player as expected.

@acidbyt3 That should now be fixed in the latest developer build

**Comment by vulunijo** [comment] 2016-07-11 11:45
No not fixed
tab doesn't work

**Closed** 2018-04-07 10:48 UTC
Labels: bug
