### ISSUE TITLE
reason.yml bug also whats perm to see ban message in chat 

### ISSUE THREAD

**Issue by Twi5TeD** [BanManagement/BanManager#333] opened 2015-07-27 23:17 UTC
still doesnt work i do hacking: Using a hacked client in the reason file and do /ban playername #hacking and it says banned player for #hacking and not the reason from the reasonfile and does anyone know the perm to see bans in what like if i do /ban name test others can see it?

**Comment by confuser** [comment] 2015-07-28 09:45
Duplicate of #332

**Comment by confuser** [comment] 2015-07-28 09:45
Check the bm.nofity permissions at http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/

**Closed by confuser** 2015-07-28 09:45 UTC
