### ISSUE TITLE
Proposal for tempmute with online expires timer and huge BUG.

### ISSUE THREAD

**Issue by Kixot14** [BanManagement/BanManager#424] opened 2015-10-15 10:25 UTC
Can you add a tempmute timer, which expires only when player online?? 
When moderator muted some player for 24 hour, and that player 24 hour dont be online, that punish for him don't have any sense!
Maybe u can add individual command for online-expires-tempmute, or something like additional flag to command ??
/tempmute <player> <timeDiff> <reason> - usual tempmute command
/tempmute <player> -oe <timeDiff> <reason> - tempmute command with online expires timer

And one more: I thank you for this plugin, but did you will to fix someday that f*cking bug with UUID?? In my server only 10% players have mojang accounts. What should i do??

**Comment by confuser** [comment] 2015-10-15 10:31
Duplicate of #211 

As for the UUID issue, it's a problem down at the Bukkit side, it is case sensitive when generating UUIDs. The solution, run an online mode server, or feel free to make a pull request with a fix.

**Closed by confuser** 2015-10-15 10:31 UTC

**Comment by Kixot14** [comment] 2015-10-15 10:47
But why your plugin can't just use another mode, and give ban for players by their nicknames?? (for offline-mode servers)

**Comment by confuser** [comment] 2015-10-15 10:52
I don't officially support offline mode servers on principal. Basic offline support mode was added through a pull request, and I'd much rather work on new features than attempt to support a very legally grey area subset of servers.

**Comment by Kixot14** [comment] 2015-10-15 11:19
Sure you're right, noone dont like piracy... But when peoples barely have salary - 120eur, Not everyone wants to give 20e for the game...

So, maybe u can fix that at order ??

**Comment by Kixot14** [comment] 2015-10-15 11:25
If I understood correctly, that bug happen only when player join first time at one nickname, and second time with the same nickname, but with another case?? And then BM can't check this acc??

**Comment by EvilOlaf** [comment] 2015-10-15 12:58
Unfortunately @confuser does not do any paid coding. See https://github.com/BanManagement/BanManager/issues/373

**Comment by Kixot14** [comment] 2015-10-15 22:05
With IpBan this bug with UUID is not happen, right?
Maybe u can add Temp-Ip-Mute and Temp-Ip-Warn at least ??

**Comment by Kixot14** [comment] 2015-10-16 12:52
Please, say me when specifically this bug is happens? In whitch circumstances ??

**Comment by Kakifrucht** [comment] 2015-10-16 13:11
Why don't you use a different banning solution? BanManager is obviously not suited for your needs, there are lots of other plugins out there.
Also, using IPBans is not recommended, as most people have dynamic ips.

**Comment by Kixot14** [comment] 2015-10-16 13:19
I have tried a lot of Ban-plugins and only BM meets all my needs.
Maybe this can help me? - http://www.curse.com/bukkit-plugins/minecraft/uuid#t1:description

**Comment by Kixot14** [comment] 2015-10-18 11:27
So what did you say about this plugin ??
http://www.curse.com/bukkit-plugins/minecraft/uuid#t1:description

**Comment by EvilOlaf** [comment] 2015-10-18 11:44
As written above  offline mode support is not directly supported so you may ask the author of this particular plugin of this would solve your problems.
