### ISSUE TITLE
Parts of reasons is being removed

### ISSUE THREAD

**Issue by jaboy** [BanManagement/BanManager#574] opened 2016-04-03 19:35 UTC
If you are making a reason that contains a parenthesis (), the parenthesis and everything inside it will be ignored.

i'm using banmanager v5.9.0

(example below)
```
[21:31:03] [Server thread/INFO]: weboy issued server command: /tempban the_cam_guy 1s test, dont mind this (really dont mind this)
[21:31:03] [Craft Scheduler Thread - 271/INFO]: The_Cam_guy has been banned by weboy
 - Reason: test, dont mind this
 - Expiry: 1 second
```

**Comment by manuelgu** [comment] 2016-04-03 19:39
This is a feature. In your case there was a player note created called "really dont mind this".
This can be disabled in the config [here](https://github.com/BanManagement/BanManager/blob/master/src/main/resources/config.yml#L157).

**Comment by xILukasIx** [comment] 2016-04-03 20:38
I have noticed that even when setting this to "false", it'll still create the note and shorten the reason.

**Comment by confuser** [comment] 2016-04-03 20:39
Duplicate of #570

**Closed by confuser** 2016-04-03 20:39 UTC
Labels: question
