### ISSUE TITLE
None of the commands work

### ISSUE THREAD

**Issue by Xofter** [BanManagement/BanManager#357] opened 2015-08-05 15:39 UTC
I Get this error while starting the server. Last night everything was working fine, restarted the server (didnt change anything), and now cant  use any of the commands. Tried 5.6.1, 5.60, 5.70 builds
[18:33:55] [Server thread/ERROR]: Error occurred while enabling BanManager v5.7.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.storage.PlayerBanStorage.<init>(PlayerBanStorage.java:49) ~[?:?]
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:405) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:125) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by confuser** [comment] 2015-08-07 09:26
Duplicate of #330 which contains a solution however it seems some people have something that is removing rows from their players table causing this problem. BanManager never deletes anything from the players table, but I'll leave this issue open so the plugin can be more robust.

**Closed** 2015-08-16 09:34 UTC
Labels: bug
