### ISSUE TITLE
WebUI install on dedicated server?

### ISSUE THREAD

**Issue by KookosPahkina** [BanManagement/BanManager#484] opened 2016-01-02 09:40 UTC
So umm i installed my banmanger to /var/www/html/banmanager
so i go to the address xxx.xxx.xx.xx/banmanager it works just fine, when i try to go into the home tab or something else it just keeps saying "The requested URL /index.php was not found on this server."
same for admin panel etc, so how am i supposed to install this? lol.. followed every single step on the installion guide. I am using Centos 7 
EDIT:
i was using an older version, and i tried with the newest version. still the same problem except the message changed to this now. 
The requested URL /banmanager/index.php was not found on this server.

**Comment by confuser** [comment] 2016-01-02 13:35
Duplicate of https://github.com/BanManagement/BanManager-WebUI/issues/120

**Closed** 2016-01-02 13:35 UTC
