### ISSUE TITLE
Error sometimes posted in console

### ISSUE THREAD

**Issue by CloudeLecaw** [BanManagement/BanManager#351] opened 2015-08-04 09:01 UTC
[03:17:22] [Craft Scheduler Thread - 267/WARN]: Exception in thread "Craft Scheduler Thread - 267" 
[03:17:22] [Craft Scheduler Thread - 267/WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.6.1 generated an exception while executing task 31
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.PlayerBanData
	at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
	at me.confuser.banmanager.runnables.ExpiresSync.run(ExpiresSync.java:37)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
	at com.mysql.jdbc.ResultSetImpl.first(ResultSetImpl.java:1164)
	at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.first(JdbcDatabaseResults.java:58)
	at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:79)
	at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
	... 6 more

**Comment by EvilOlaf** [comment] 2015-08-04 09:07
Pretty much related to https://github.com/BanManagement/BanManager/issues/321

**Comment by confuser** [comment] 2015-08-04 11:19
Duplicate of #321

**Closed by confuser** 2015-08-04 11:19 UTC
