### ISSUE TITLE
Tabcomplete error

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#821] opened 2019-12-11 16:27 UTC
# Issue report

**Tell us about your environment**

* **Server Software:** Paper
* **Server Version:** 1.13.2
* **BanManager Version:** 7.0.0-SNAPSHOT (latest build)

* **Online/Offline mode**: Offline mode

**Describe your issue:** 
When I try to tabcomplete names after command /ban /kick /bminfo etc. it throws that error to console https://pastebin.com/cQsZqrgj and says this in chat:
![obrazek](https://user-images.githubusercontent.com/42073765/70639664-1473c100-1c3b-11ea-92ec-4b68cb262b9e.png)

When I deleted BanManager and kept Essentials on my test server, it worked fine.

**Comment by Nety01** [comment] 2019-12-12 18:20
Also can't perform the command

**Comment by confuser** [comment] 2019-12-21 10:55
I'm not able to reproduce this issue. Could you confirm that `onlineMode` in your config.yml file is set to false AND your server.properties file?

**Comment by Nety01** [comment] 2019-12-21 11:09
Sure. 

`BanManager/config.yml - onlineMode: false`
`/server.properties - online-mode=false`

It also may be possible because I'm using dev build of EssentialsX, I'm using this right now https://ci.ender.zone/job/EssentialsX/792/

**Comment by confuser** [comment] 2019-12-21 11:23
Is `offlineAutoComplete` set to false in your BanManager/config.yml?

**Comment by Nety01** [comment] 2019-12-21 11:27
Yes `offlineAutoComplete: false`

**Comment by confuser** [comment] 2019-12-21 12:02
Should be resolved in latest build. Appears to have been an issue with generating offline mode uuids.

**Closed by confuser** 2019-12-21 12:02 UTC
Labels: bug
