### ISSUE TITLE
error on start up 

### ISSUE THREAD

**Issue by kemit-the-frog** [BanManagement/BanManager#593] opened 2016-04-18 18:15 UTC
[14:11:47] [Server thread/INFO]: [BanManager] Enabling BanManager v5.9.0
[14:11:48] [Server thread/WARN]: 49 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-1 - Started.

I keep getting this error when i try to start the server, all i did was install the plugin and give it mysql login. What does it mean?

**Comment by EvilOlaf** [comment] 2016-04-18 18:18
This is not an error but INFO.

**Comment by kemit-the-frog** [comment] 2016-04-18 18:19
what does it mean?

**Comment by EvilOlaf** [comment] 2016-04-18 18:24
Hikari is the library that is used to create a bridge between BM and your MySQL server. The message itself is purely informational and means that the connection pool to the MySQL server has started.

**Comment by confuser** [comment] 2016-04-19 09:21
Duplicate of #585.

**Closed by confuser** 2016-04-19 09:21 UTC
