### ISSUE TITLE
Some errors on autocomplete

### ISSUE THREAD

**Issue by JANEXLEBJAKOT** [BanManagement/BanManager#444] opened 2015-11-04 16:22 UTC
Every time i try to autocomplete with tab someone's nickname plugin spams in chat:
http://hastebin.com/vabuxasuso.avrasm

**Comment by EvilOlaf** [comment] 2015-11-04 16:27
https://github.com/BanManagement/BanManager/issues/213

**Comment by frdmn** [comment] 2015-11-04 18:03
Duplicate of #213

**Comment by JANEXLEBJAKOT** [comment] 2015-11-04 21:20
But 213 is closed and not fixed.

**Comment by JANEXLEBJAKOT** [comment] 2015-11-04 21:32
But #213 and #210 are closed and not fixed.

**Comment by frdmn** [comment] 2015-11-05 08:14
Whoops, my bad!

**Comment by EvilOlaf** [comment] 2015-11-05 08:27
Afair because this was no issue with neither  bm nor Pex. Maybe essentials or cb itself.

**Comment by confuser** [comment] 2015-11-05 15:10
The cause is most likely Essentials. Try and update to the latest version if you're running 1.8.

As far as a fix goes, there's not so much I can do on the BM end if other plugins interfere.

**Closed by confuser** 2015-11-05 15:10 UTC
Labels: duplicate

**Comment by EvilOlaf** [comment] 2015-11-05 15:24
I'll ask EssentialsX. Maybe they can fix this finally.

**Comment by SupaHam** [comment] 2015-11-05 15:46
@confuser Just curious, why can't you null check command#getPermissions()?

**Comment by confuser** [comment] 2015-11-05 16:00
@SupaHam I shouldn't need to, as all BanManager commands have a permission associated with it. If the NPE throws, it means another plugin has overridden the command, but not the tab executor. This would also cause players without the permission to be able to auto complete offline player names, unless the entire thing returns an empty list at that point.

**Comment by SupaHam** [comment] 2015-11-05 16:19
What command is causing this issue?

**Comment by EvilOlaf** [comment] 2015-11-05 16:28
Here this has been reproduced with `/unban` https://github.com/BanManagement/BanManager/issues/210 
At PEX I have a report with `/ban` https://github.com/PEXPlugins/PermissionsEx/issues/1956
