### ISSUE TITLE
Error after server restart

### ISSUE THREAD

**Issue by Theepwner** [BanManagement/BanManager#395] opened 2015-09-12 21:35 UTC
http://hastebin.com/arujujenul.avrasm

Build 179

**Comment by Kakifrucht** [comment] 2015-09-12 22:39
Does this happen every time or only once? Did it generate followup issues?

**Comment by confuser** [comment] 2015-09-12 23:05
Duplicate of #321

**Comment by EvilOlaf** [comment] 2015-09-12 23:05
Related #321?

**Closed** 2015-09-12 23:05 UTC
