### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by bingoberra** [BanManagement/BanManager#504] opened 2016-01-15 21:27 UTC
The plugin is REALLY slow on startup.

15.01 22:46:55 [Server] INFO Loaded 0 ip range bans into memory
15.01 22:46:55 [Server] INFO Loaded 86 ip bans into memory
15.01 22:46:38 [Server] INFO Loaded 6 mutes into memory
15.01 22:46:36 [Server] INFO Loaded 392 bans into memory
15.01 22:44:26 [Server] INFO Enabling BanManager v5.6.0

This was not an issue on earlier version. It takes about 2 1/2 minutes for it to load up! Which is a really long time for any plugin. 

I'm using Spigot 1.8.7 & BanManager v5.6.0.

**Comment by Kakifrucht** [comment] 2016-01-16 00:08
a) version updated, b) probably issue with database. Is it hosted locally?

**Comment by confuser** [comment] 2016-01-18 15:30
Closing. This isn't an issue with the plugin, it's due to a slow database connection.

If anyone does run into performance problems with the plugin itself or due to the way a particular feature is implemented, and not simply because of a slow connection, then by all means open an issue; I'd be interested in hearing it.

**Closed by confuser** 2016-01-18 15:30 UTC

**Comment by bingoberra** [comment] 2016-01-24 18:15
This is not an issue with the database connection.
The plugin is REALLY slow on startup.

15.01 22:46:55 [Server] INFO Loaded 0 ip range bans into memory
15.01 22:46:55 [Server] INFO Loaded 86 ip bans into memory
15.01 22:46:38 [Server] INFO Loaded 6 mutes into memory
15.01 22:46:36 [Server] INFO Loaded 392 bans into memory
15.01 22:44:26 [Server] INFO Enabling BanManager v5.6.0

#READ THIS PART PLEASE: #
This was not an issue on earlier version. It takes about 2 1/2 minutes for it to load up! Which is a really long time for any plugin.

I'm using Spigot 1.8.7 & BanManager v5.6.0.

**Comment by confuser** [comment] 2016-01-24 19:31
> This was not an issue on earlier version.
Which version?

Ping your MySQL database and paste the output here
`ping whateverTheHostIs.com`

I can't reproduce this, Frostcast has over 1k bans on one of our servers and it loads in less than a second.

**Comment by confuser** [comment] 2016-01-24 19:44
Also, the latest version is `v5.8.0` not `v5.6.0`, ensure you update to the latest version before reporting bugs.

**Comment by bingoberra** [comment] 2016-01-25 00:56
Thanks, I tried the newest version before. It didn't work at all. I'm using spigot 1.8.7 with java 7.
But this time I got it working! This happend:
"[Server] WARN 75 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-0 - is starting."

Stuck like this for about 2 minutes while apparently loading bans, mutes and warnings into memory!

**Comment by confuser** [comment] 2016-01-25 09:52
> Ping your MySQL database and paste the output here
ping whateverTheHostIs.com

**Comment by bingoberra** [comment] 2016-01-25 14:14
According to our host your plugin requires way to many connection at the same time. 
How do I do that?

**Comment by confuser** [comment] 2016-01-25 14:17
The amount of connections is configurable in your `config.yml` file. The default is 10, that's hardly too many.

Do you have SSH access?
