### ISSUE TITLE
Configuration option "onlineMode" still relevant?

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#500] opened 2016-01-09 18:39 UTC
I was comparing my config.yml file to the latest version while investigating another issue, and noticed that I have this option specified in my config.yml file and it is not in the latest version of config.yml created by the plugin on first run.  Should this be removed from my config file?  What was it for?  I honestly don't remember...

**Comment by confuser** [comment] 2016-01-09 18:41
Duplicate of #496

**Closed by confuser** 2016-01-09 18:41 UTC
