### ISSUE TITLE
how can i disable the report command so another plugin can be used

### ISSUE THREAD

**Issue by Twi5TeD** [BanManagement/BanManager#538] opened 2016-02-29 19:37 UTC
i have a plugin that uses the command report but banmanager is taking it so is there anyway i can disable the command?

**Comment by EvilOlaf** [comment] 2016-02-29 19:52
https://github.com/BanManagement/BanManager/issues/532

**Comment by confuser** [comment] 2016-03-01 10:00
Duplicate of #486

**Closed by confuser** 2016-03-01 10:00 UTC
