### ISSUE TITLE
Repo for web UI

### ISSUE THREAD

**Issue by kaithar** [BanManagement/BanManager#126] opened 2015-01-02 00:14 UTC
Hi there, I'm after making some changes to the UI, but I can't seem to find a repo for it.  Does one exist?
Obviously it's easier to release my changes and offer patches if there is one.

**Comment by frdmn** [comment] 2015-01-12 10:48
@confuser I too search the repository for the web interface. Since the v5 is using new MySQL fields, I doubt the old one (dev.bukkit.org release) still works. 

Where can I find a web UI for the updated table names?

**Comment by confuser** [comment] 2015-01-12 12:46
The v4 and below version can be found in the feature/pre-uuid branch.

The interface doesn't currently exist for v5. The old interface is pretty rubbish code quality wise, and was only ever meant to be a quick prototype, not something that was intended to be released.

Someone did start work on a new interface some time ago, but it never got very far.
https://github.com/ftbastler/Ban-Management-Web

**Comment by frdmn** [comment] 2015-01-12 12:53
@confuser Okay, so since we now use v5. When can we expect an new official web UI? 

Or perhaps I ask different, can we except an official update here as well?

**Comment by kaithar** [comment] 2015-01-14 14:22
I've started the process of cleaning up the v4 interface, based on what's shipped with the jar.  If that version was only intended to be prototype grade I'll be a little more aggressive in my refactors.

Do you have a roadmap for v5?  Particularly, http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/ says it is missing the database and api?

**Comment by confuser** [comment] 2015-01-14 15:16
@kaithar BmAPI is in the latest dev builds, and it's missing external ban functionality. But with regards to the web interface, nothing currently missing in v5 should affect it, as the web interface just reads the database directly.

I have in fact written a v5 web interface over at http://www.frostcast.net/bans however, it's written in Node.js but it's locked in with the Frostcast site architecture, otherwise I would release it.

The most notable changes in v5 are the tables, all bans/mutes etc are referenced by UUIDs instead of names. To retrieve the names, it's just a simple join.

```sql
SELECT p.name, a.name AS actor, b.reason, b.created FROM ?? b JOIN ?? p ON b.player_id = p.id JOIN ?? a ON b.actor_id = a.id WHERE p.name = ?'
```

**Comment by kaithar** [comment] 2015-01-15 13:56
Ah, I think I see the confusion...
> Some features are also missing such as external database and the BmAPI, but they will be added in future releases.
That's the external aggregated ban database, not the mysql bit of it.  Ok.

It shouldn't be too bad to abstract away the differences between v4 and v5, though it'd have to be a config switch since I don't really like the idea of detecting the version via schema inspection.

**Comment by confuser** [comment] 2015-01-15 14:06
Just force the user to choose which version the server is when they add it.

**Comment by frdmn** [comment] 2015-01-15 14:18
@kaithar I'll watch your repo. Good look with the development :)

**Comment by confuser** [comment] 2015-01-15 15:02
@kaithar I know the other project was looking to use Laravel. I'm not a massive fan of massive bloated frameworks though.

Perhaps it'll be a lot tidier to use a more MVC like pattern, via a route manager like slim? http://www.slimframework.com/

The project will also need to be updated to use either PDO or MySQLi, as mysql_* has been removed in the current stable version of PHP and I know it has caused people problems.

It'd be better for the new Web project to only support v5 going onwards, otherwise it'll cause a lot of headaches in the future.

**Comment by kaithar** [comment] 2015-01-15 15:43
Personally I've yet to find a PHP framework that I entirely like, most MVC frameworks are so excessively opinionated that trying to operate outside of their expectations is very painful.  http://www.codeigniter.com/ is probably one of the few that has a good feature set without making too many assumptions for you.

I think if I were doing a complete rewrite purely for my own purposes I'd be inclined towards a python based project, but sadly php is definitely the easiest for general use.  In the interests of time I'm going to continue along the path of refactoring for the moment.

Making it v5 only does simplify things if a full ORM is used, but without one it's actually not that bad to abstract it away in the process of refactoring the embedded sql to some where nice.

**Comment by frdmn** [comment] 2015-01-23 13:24
@confuser regarding the NodeJS frontend. Would you mind releasing it? Would love to clean it up for you and remove the customizions for Frostcast.

**Comment by frdmn** [comment] 2015-01-26 14:16
@kaithar I "hotfixed" the current WebUI for version 5 for now. You can find the repository over here: https://github.com/yeahwhat-mc/BanManager-WebUI

@confuser I hope it's okay to release it for the public. If so, maybe you can add a license via PR. :)

**Comment by confuser** [comment] 2015-01-26 15:43
@frdmn I'm currently refactoring a lot of the site, I'll release it when I can.

It looks good, one thing that does however need changing is to either use MySQLi or PDO instead of mysql_ functions, as they were removed in the most recent stable version of PHP. I've had a few tickets been raised because of it too.

**Comment by frdmn** [comment] 2015-01-26 17:07
@confuser Added on my todo :)

**Comment by frdmn** [comment] 2015-01-29 12:49
Impelemented, also fixed some other little bugs and annoyances :)

**Comment by confuser** [comment] 2015-01-30 11:49
:+1:

**Comment by Kakifrucht** [comment] 2015-02-02 19:30
mysql_ functions were removed? Isn't it just apt-get install php5-mysql? Worked for me.

**Comment by frdmn** [comment] 2015-02-02 20:03
@Kakifrucht The `php5-mysql` package also contains the `mysqli_` functions that you need now, so you are good to go. For more information about Ubuntu packages: 

http://packages.ubuntu.com/en/lucid/php/php5-mysql

**Comment by Kakifrucht** [comment] 2015-02-02 20:07
@frdmn Yes, what I am saying is that the old functions are basically still supported, just not in the default php package.

**Comment by frdmn** [comment] 2015-02-02 20:21
But they are marked as deprecated in PHP 5.5 and up:

http://php.net/manual/de/migration55.deprecated.php

So that's why we switched to `mysqli_`. And since you need to install `php5-mysql` anyway, it doesn't matter and no-one needs to install extra packages just for this switch.

**Comment by confuser** [comment] 2015-02-06 11:30
Official repo

https://github.com/BanManagement/BanManager-WebUI

**Closed by confuser** 2015-02-06 11:30 UTC
